### PR TITLE
Creates VPM-Compatible Package

### PR DESCRIPTION
**Pull request by momo-the-monster**
Replaces shader include paths with new Packages paths
Separates scripts into Runtime / Editor and adds Assembly Definition Files
Adds Package Manifest

### CODE REVIEW

**Comment by Float3** [comment]
The AudioLinkSandbox folder should probably either be moved into the assets folder or be part of the package.

**Comment by pema99** [comment]
AudioLinkSandbox is for stuff we don't want to distribute, so it shouldn't be in the package. It can go in the project, I think.

**Comment by pema99** [comment]
Got a bit caught up in something over the weekend. I'll take a proper look at this soon 😅 My gut feel is that it can just land as is, and we'll fix up any minor gripes with folder structure etc.

**Comment by Float3** [comment]
> AudioLinkSandbox is for stuff we don't want to distribute, so it shouldn't be in the package. It can go in the project, I think.

It is currently included in the "AudioLink Full.unitypackage", right?
Though for VPM purposes, it should probably be excluded from the package.

**Comment by pema99** [comment]
It isn't in either unitypackage

**Comment by pema99** [comment]
Waiting to sort out / investigate some remaining issues relating the install workflow

**Comment by pema99** [comment]
Merging this now, and we fix remaining issues afterwards

**Pull request merged**
