### PR TITLE
Video theme color

### PR DESCRIPTION
**Pull request by DomNomNom**
In-progress...

### CODE REVIEW

**Comment by pema99** [comment]
Are you interested in doing this, Dom? Or is it dead

**Comment by DomNomNomVR** [comment]
I think what demotivated me from going forward with this was that there didn't seem to be an universal way of getting the current video frame in VRC as there's two base video components that use different methods and many prefabs that wrap those.
it seems easier in CVR where it's always a render texture that could be dragged in

What are you thoughts on this?

Thank you for the poke about this btw.

**Comment by pema99** [comment]
Yeah, indeed, getting the video texture is annoying as hell. I think you'd basically be forced to add support for video players individually.

**Comment by DomNomNomVR** [comment]
In that case, I don't particularly mind if this gets closed to keep things clean. I might develop this on the CVR side at some point in the future.

**Comment by pema99** [comment]
Let me know if you do. I might be tempted to salvage it back into something that works for a few select video players

**Comment by pema99** [comment]
Just reopen it if you want

**Pull request closed without merging**
